### ISSUE TITLE
Invalid CSS after "i.icon.stopwatch.": expected class name, was "20:before"

### ISSUE THREAD

**Issue by birthdaycorp** [fomantic/Fomantic-UI-SASS#12]
When importing semantic-ui in my application.css file, i get this error: `Invalid CSS after "i.icon.stopwatch.": expected class name, was "20:before"`. What causes this?

**Comment by lubber-de** [comment]
This was fixed in fomantic-ui 2.8.7 by https://github.com/fomantic/Fomantic-UI/pull/1546
This port just needs an update 😉

**Comment by lubber-de** [comment]
Duplicate of #11

**Comment by shanecav84** [comment]
Thanks for adding the duplicate tag, @lubber-de.

**Comment by shanecav84** [comment]
I've released 2.8.7 which hopefully fixes the issue.
