### ISSUE TITLE
@import "semantic-ui" doesn't include Text styles

### ISSUE THREAD

**Issue by tjclifton** [fomantic/Fomantic-UI-SASS#4]
Hi,

I think this file is missing the import for the Text element styles:

https://github.com/fomantic/Fomantic-UI-SASS/blob/master/app/assets/stylesheets/semantic-ui/elements/_all.scss

Am I mistaken?

**Comment by shanecav84** [comment]
Fixed by 147288f253eda02839ca8707f7dc856949cafcfd
