### ISSUE TITLE
Include JS in Rails 6

### ISSUE THREAD

**Issue by cimm** [fomantic/Fomantic-UI-SASS#6]
Any idea how to include the JavaScript in Rails 6 with Webpack? The `//= require semantic-ui` from the [README](https://github.com/fomantic/Fomantic-UI-SASS#javascripts) no longer works, I think.

**Comment by gnomex** [comment]
I'm also interested in this integration, there are any plans to be compatible with webpacker?!

**Comment by drusepth** [comment]
There's an admittedly janky setup [in this reddit thread](https://www.reddit.com/r/rails/comments/hvrjzf/guide_fomantic_semantic_ui_from_scratch_in_rails/) that looks like it might get Fomantic ready to go in Rails 6 without this gem.

A slightly less hacky solution (that I'm currently working through the issues of, but mostly works) is to just include the JS directly from a CDN, e.g. 

    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

**Comment by shanecav84** [comment]
This gem integrates fomantic-ui with the Rails asset pipeline, which uses Sprockets for compilation. Webpacker-based compilation is a different beast.
